name: "Test workflow for git-carbon-action"
on:
  - push
  - workflow_dispatch

jobs:
  test-git-carbon-action:
    runs-on: ubuntu-latest
    name: Testing git-carbon-action
    steps:
      - uses: gregoire-mullvad/git-carbon-action
      # TODO: Check that the PR has been opened
      # TODO: Cleanup: close pr, remove branch


