name: "Test workflow for git-carbon-action"
on:
  - push
  - workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  test-git-carbon-action:
    runs-on: ubuntu-latest
    name: Testing git-carbon-action
    steps:
      - uses: actions/checkout@v4
      - uses: gregoire-mullvad/git-carbon-action@devs
      # TODO: Check that the PR has been opened
      # TODO: Cleanup: close pr, remove branch


